[package]
name = "optimizer"
version.workspace = true
edition.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }

catalog = { path = "../catalog" }
parser = { path = "../parser" }
stratifier = { path = "../stratifier" }