[workspace]
members = [
    "crates/parser",
    "crates/stratifier"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Nemo Yu"]
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
itertools = "0.14.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
thiserror = "2.0.16"
