[workspace]
members = [
    "crates/common",
    "crates/parser",
    "crates/stratifier",
    "crates/catalog",
    "crates/optimizer",
    "crates/planner",
    "crates/compiler"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Nemo Yu"]
license = "MIT"

[workspace.dependencies]
anyhow = "1.0"
clap = "4.5.51"
itertools = "0.14.0"
prettyplease = "0.2"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.110"
toml_edit = "0.23"
tracing = "0.1"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
